-- Insert all permissions from the permission hierarchy (skip if exists)
INSERT INTO public.permissions (resource, action, description) VALUES
  ('projects','read','View all projects and related details'),
  ('projects','create','Create new projects'),
  ('projects','update','Edit existing projects'),
  ('projects','delete','Delete projects'),
  ('contracts','read','View all contracts'),
  ('contracts','create','Create new contracts'),
  ('contracts','update','Edit existing contracts'),
  ('contracts','delete','Delete contracts'),
  ('time_entries','read','View time entries'),
  ('time_entries','create','Create new time entries'),
  ('time_entries','update','Edit time entries'),
  ('time_entries','delete','Delete time entries'),
  ('time_entries','edit_own','Edit your own time entries only'),
  ('time_entries','view_all','View time entries from all employees'),
  ('time_entries','read_all','View all time entries'),
  ('time_entries','read_own','View own time entries'),
  ('time_entries','manage','Full management of time entry system'),
  ('quotes','read','View all quotes and proposals'),
  ('quotes','create','Create new quotes'),
  ('quotes','update','Edit quotes'),
  ('quotes','delete','Delete quotes'),
  ('quotes','send','Send quotes to clients via email'),
  ('payables','read','View accounts payable records'),
  ('payables','create','Create new payable entries'),
  ('payables','update','Edit payable records'),
  ('payables','delete','Delete payable records'),
  ('payables','approve','Approve payable payments'),
  ('receivables','read','View accounts receivable records'),
  ('receivables','create','Create new receivable entries'),
  ('receivables','update','Edit receivable records'),
  ('receivables','delete','Delete receivable records'),
  ('assets','read','View company assets and depreciation'),
  ('assets','create','Register new assets'),
  ('assets','update','Edit asset information'),
  ('assets','delete','Delete asset records'),
  ('petty_cash','read','View petty cash transactions'),
  ('petty_cash','create','Record petty cash transactions'),
  ('petty_cash','update','Edit petty cash transactions'),
  ('petty_cash','delete','Delete petty cash transactions'),
  ('debit_cards','read','View debit card transactions'),
  ('debit_cards','create','Add debit card transactions'),
  ('debit_cards','update','Edit card transactions'),
  ('debit_cards','delete','Delete card transactions'),
  ('accounts','read','View bank account information'),
  ('accounts','create','Add new bank accounts'),
  ('accounts','update','Edit bank account details'),
  ('accounts','delete','Delete bank accounts'),
  ('loans','read','View loan information'),
  ('loans','create','Create new loan records'),
  ('loans','update','Edit loan information'),
  ('loans','delete','Delete loan records'),
  ('purchase_orders','read','View purchase orders'),
  ('purchase_orders','create','Create new purchase orders'),
  ('purchase_orders','update','Edit purchase orders'),
  ('purchase_orders','delete','Delete purchase orders'),
  ('purchase_orders','approve','Approve purchase orders for processing'),
  ('subscriptions','read','View subscription information'),
  ('subscriptions','create','Add new subscriptions'),
  ('subscriptions','update','Edit subscription details'),
  ('subscriptions','delete','Delete subscriptions'),
  ('employees','read','View basic employee information'),
  ('employees','read_sensitive','View salary, SSN, and other sensitive data'),
  ('employees','create','Add new employees'),
  ('employees','update','Edit employee information'),
  ('employees','delete','Delete employee records'),
  ('employee_onboarding','manage','Manage employee onboarding process'),
  ('employee_onboarding','view','View onboarding status and progress'),
  ('payroll','read','View payroll information'),
  ('payroll','create','Create payroll entries'),
  ('payroll','update','Edit payroll information'),
  ('payroll','process','Process and finalize payroll'),
  ('payroll','approve','Approve payroll for payment'),
  ('pto','read_all','View PTO requests from all employees'),
  ('pto','read_own','View own PTO requests and balance'),
  ('pto','create','Submit PTO requests'),
  ('pto','approve','Approve or reject PTO requests'),
  ('pto','delete','Delete PTO requests'),
  ('vendors','read','View vendor information'),
  ('vendors','create','Add new vendors'),
  ('vendors','update','Edit vendor information'),
  ('vendors','delete','Delete vendor records'),
  ('notes','read','View notes and comments'),
  ('notes','create','Create new notes'),
  ('notes','update','Edit notes'),
  ('notes','delete','Delete notes'),
  ('todos','read','View to-do items'),
  ('todos','create','Create new to-do items'),
  ('todos','update','Edit to-do items'),
  ('todos','delete','Delete to-do items'),
  ('analytics','view','Access main analytics dashboard'),
  ('analytics','read','View financial analytics and reports'),
  ('analytics','manage','Full analytics management and configuration'),
  ('documents','read','View documents in the document bank'),
  ('documents','upload','Upload new documents'),
  ('documents','update','Edit document metadata'),
  ('documents','delete','Delete documents'),
  ('documents','download','Download documents')
ON CONFLICT DO NOTHING;

-- Grant ALL permissions to Super Admin role
INSERT INTO public.role_permissions (role_id, permission_id)
SELECT r.id, p.id
FROM public.roles r, public.permissions p
WHERE r.name = 'Super Admin'
ON CONFLICT DO NOTHING;

SELECT COUNT(*) AS total_permissions FROM public.permissions;
SELECT COUNT(*) AS super_admin_permissions
FROM public.role_permissions rp
JOIN public.roles r ON r.id = rp.role_id
WHERE r.name = 'Super Admin';
