-- ============================================================
-- PUBLIC SCHEMA: shared system/auth/RBAC tables (29 tables)
-- Business tables live in tenant schemas only
-- ============================================================

CREATE TABLE IF NOT EXISTS active_sessions (id SERIAL, user_id integer NOT NULL, session_token uuid NOT NULL DEFAULT gen_random_uuid(), expires_at timestamp without time zone NOT NULL, ip_address character varying(100), user_agent text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS active_timers (id SERIAL, employee_id integer NOT NULL, time_entry_id integer NOT NULL, started_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, is_on_break boolean DEFAULT false, total_break_time_minutes integer DEFAULT 0, last_break_start timestamp without time zone);
CREATE TABLE IF NOT EXISTS announcements (id SERIAL, title character varying(255) NOT NULL, content text NOT NULL, author_id integer, priority character varying(20) DEFAULT 'normal'::character varying, category character varying(50), start_date timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP, end_date timestamp without time zone, target_audience jsonb DEFAULT '{"type": "all"}'::jsonb, is_active boolean DEFAULT true, views_count integer DEFAULT 0, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS application_settings (id SERIAL, setting_key character varying(100) NOT NULL, setting_value text, description text, updated_by integer, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS dashboard_admins (id SERIAL, name character varying(255) NOT NULL, email character varying(255) NOT NULL, password_hash character varying(255) NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, last_login_at timestamp without time zone);
CREATE TABLE IF NOT EXISTS email_log (id SERIAL, employee_id integer, email_type character varying(50) NOT NULL, recipient_email character varying(255) NOT NULL, subject character varying(255), sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, delivery_status character varying(20) DEFAULT 'sent'::character varying, error_message text, metadata jsonb);
CREATE TABLE IF NOT EXISTS employee_audit_log (id SERIAL, employee_id integer, action character varying(100) NOT NULL, resource_type character varying(50), resource_id integer, old_value jsonb, new_value jsonb, ip_address character varying(45), user_agent text, session_id character varying(255), status character varying(20) DEFAULT 'success'::character varying, error_message text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS employee_documents (document_id SERIAL, employee_id integer NOT NULL, document_type character varying(50) NOT NULL, document_category character varying(50), file_name character varying(255) NOT NULL, original_name character varying(255) NOT NULL, file_path character varying(500) NOT NULL, file_size integer NOT NULL, mime_type character varying(100) NOT NULL, description text, uploaded_by integer, uploaded_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, expires_at timestamp without time zone);
CREATE TABLE IF NOT EXISTS employee_notifications (notification_id SERIAL, employee_id integer NOT NULL, notification_type character varying(50) NOT NULL, title character varying(255) NOT NULL, message text, link character varying(500), priority character varying(20) DEFAULT 'normal'::character varying, is_read boolean DEFAULT false, is_archived boolean DEFAULT false, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, read_at timestamp without time zone, expires_at timestamp without time zone);
CREATE TABLE IF NOT EXISTS employee_portal_settings (id SERIAL, employee_id integer NOT NULL, theme character varying(20) DEFAULT 'light'::character varying, dashboard_layout jsonb DEFAULT '{"widgets": ["stats", "notes", "calendar", "announcements"]}'::jsonb, email_notifications boolean DEFAULT true, push_notifications boolean DEFAULT false, language character varying(10) DEFAULT 'en'::character varying, timezone character varying(50) DEFAULT 'UTC'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, email_preferences jsonb DEFAULT '{"pto_notifications": true, "time_entry_reminders": true, "announcement_notifications": true}'::jsonb, show_in_directory boolean DEFAULT true, hide_phone_in_directory boolean DEFAULT false);
CREATE TABLE IF NOT EXISTS enterprise_inquiries (id SERIAL, name character varying(100) NOT NULL, email character varying(100) NOT NULL, phone character varying(50) NOT NULL, company_name character varying(100) NOT NULL, requirements text NOT NULL, status character varying(20) DEFAULT 'pending'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS messages (id SERIAL, user_id integer, user_name character varying(255) NOT NULL, message text NOT NULL, channel character varying(50) DEFAULT 'general'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notifications (id SERIAL, type character varying(60) NOT NULL, user_id integer, title character varying(255) NOT NULL, message text NOT NULL, metadata jsonb DEFAULT '{}'::jsonb, is_read boolean NOT NULL DEFAULT false, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS packages (id SERIAL, name character varying(50) NOT NULL, display_name character varying(100) NOT NULL, price_monthly numeric(10,2) DEFAULT 0, price_yearly numeric(10,2) DEFAULT 0, features jsonb NOT NULL DEFAULT '{}'::jsonb, is_active boolean DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, max_users integer, description text);
CREATE TABLE IF NOT EXISTS password_history (id SERIAL, user_id integer NOT NULL, password_hash text NOT NULL, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payslip_documents (document_id SERIAL, payslip_id integer NOT NULL, file_path character varying(500) NOT NULL, file_name character varying(255) NOT NULL, file_type character varying(10) DEFAULT 'PDF'::character varying, file_size bigint, generated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payslip_signature_tokens (id SERIAL, payslip_id integer NOT NULL, employee_id integer NOT NULL, token character varying(255) NOT NULL, expires_at timestamp without time zone NOT NULL, used_at timestamp without time zone, is_used boolean DEFAULT false, ip_address character varying(45), user_agent text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payslip_signatures (signature_id SERIAL, payslip_id integer NOT NULL, signer_user_id integer NOT NULL, signer_role character varying(50) NOT NULL, signature_hash character varying(255) NOT NULL, signed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, ip_address character varying(45));
CREATE TABLE IF NOT EXISTS payslips (payslip_id SERIAL, employee_id integer NOT NULL, payslip_month integer NOT NULL, payslip_year integer NOT NULL, basic_salary numeric(15,2) NOT NULL, allowances jsonb DEFAULT '{}'::jsonb, gross_salary numeric(15,2) NOT NULL, epf_employee_deduction numeric(15,2) DEFAULT 0, epf_employee_rate numeric(5,2) DEFAULT 8.00, other_deductions jsonb DEFAULT '{}'::jsonb, total_deductions numeric(15,2) DEFAULT 0, epf_employer_contribution numeric(15,2) DEFAULT 0, etf_employer_contribution numeric(15,2) DEFAULT 0, net_salary numeric(15,2) NOT NULL, status character varying(50) DEFAULT 'DRAFT'::character varying, rejection_reason text, created_by_user_id integer NOT NULL, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS permissions (id SERIAL, resource character varying(50) NOT NULL, action character varying(20) NOT NULL, description text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS project_items (project_id integer NOT NULL, requirements text NOT NULL, service_category text NOT NULL, unit_cost numeric NOT NULL, requirement_type text NOT NULL);
CREATE TABLE IF NOT EXISTS rbac_audit_log (id SERIAL, user_id integer, action character varying(100) NOT NULL, details jsonb, ip_address character varying(50), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS role_permissions (role_id integer NOT NULL, permission_id integer NOT NULL, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS roles (id SERIAL, name character varying(50) NOT NULL, description text, is_system_role boolean DEFAULT false, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sub_users (id SERIAL, main_user_id integer NOT NULL, name character varying(255) NOT NULL, email character varying(255), role character varying(100) DEFAULT 'user'::character varying, department character varying(100), is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS tenants (id SERIAL, name character varying(100) NOT NULL, schema_name character varying(100) NOT NULL, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS upgrade_requests (id SERIAL, user_id integer, user_name character varying(100) NOT NULL, user_email character varying(100) NOT NULL, current_plan character varying(50), requested_plan character varying(50) NOT NULL, requirements text, status character varying(20) DEFAULT 'pending'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS user_roles (user_id integer NOT NULL, role_id integer NOT NULL, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS users (id SERIAL, name text NOT NULL, email text NOT NULL, password_hash text NOT NULL, role text DEFAULT 'user'::text, role_id integer, tenant_id integer, source character varying(50) DEFAULT NULL::character varying, password_must_change boolean DEFAULT false, account_status character varying(20) DEFAULT 'active'::character varying, created_at timestamp without time zone DEFAULT now(), package_id integer, package_status character varying(50) DEFAULT 'active'::character varying, no_of_users integer DEFAULT 1, status_changed_at timestamp without time zone, status_changed_by integer, status_reason text, subscription_end_date date, plan_type character varying(50), purchase_date date, company_type character varying(50));

-- ============================================================
-- TENANT SCHEMA TEMPLATE: business tables (34 tables)
-- Applied per-tenant with: SET search_path TO tenant_<name>
-- ============================================================

CREATE TABLE IF NOT EXISTS assets (id SERIAL, asset_name text NOT NULL, value numeric NOT NULL, purchase_date date NOT NULL, depreciation_method text, salvage_value numeric, useful_life integer, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS bank_transactions (id SERIAL, bank_account_id integer NOT NULL, transaction_type character varying(10), amount numeric(15,2) NOT NULL, description text, transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS banks (id SERIAL, bank_name character varying(100) NOT NULL, branch character varying(100), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS company_bank_accounts (id SERIAL, bank_id integer NOT NULL, account_number character varying(50) NOT NULL, account_name character varying(100), opening_balance numeric(15,2) NOT NULL, current_balance numeric(15,2) NOT NULL, is_active boolean DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS contract_items (contract_id integer NOT NULL, requirements text NOT NULL, service_category text NOT NULL, unit_cost numeric NOT NULL, requirement_type text NOT NULL);
CREATE TABLE IF NOT EXISTS contracts (contract_id SERIAL, project_id integer NOT NULL, contract_name character varying(200) NOT NULL, customer_name character varying(200), description text, initial_cost_budget numeric(12,2) DEFAULT 0, extra_budget_allocation numeric(12,2) DEFAULT 0, payment_type character varying(50), status character varying(50) DEFAULT 'pending'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS debit_card (id SERIAL, bank_account_id integer NOT NULL, card_number_last4 character varying(4) NOT NULL, card_holder_name character varying(100) NOT NULL, expiry_date date NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS debit_cards (id SERIAL, bank_account_id integer NOT NULL, card_number_last4 character varying(4) NOT NULL, card_holder_name character varying(100) NOT NULL, expiry_date date NOT NULL, is_active boolean NOT NULL DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS documents (id SERIAL, document_name character varying(255) NOT NULL, original_filename character varying(255) NOT NULL, file_type character varying(100) NOT NULL, file_size integer NOT NULL, file_data bytea NOT NULL, uploaded_by integer NOT NULL, upload_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP, description text);
CREATE TABLE IF NOT EXISTS employees (id SERIAL, employee_number character varying(50), first_name character varying(100) NOT NULL, last_name character varying(100) NOT NULL, email character varying(150), phone character varying(30), dob date, nic character varying(50), address text, role character varying(100), designation character varying(150), employee_department character varying(100), tax character varying(100), hire_date date, manager_id integer, user_id integer, tenant_id integer, is_active boolean DEFAULT true, base_salary numeric(12,2) DEFAULT 0, allowances jsonb DEFAULT '{}'::jsonb, epf_enabled boolean DEFAULT true, epf_contribution_rate numeric(5,2) DEFAULT 8.00, etf_enabled boolean DEFAULT true, pto_allowance integer DEFAULT 20, bank_name character varying(100), bank_account_number character varying(50), bank_branch character varying(100), emergency_contact_name character varying(100), emergency_contact_relationship character varying(50), emergency_contact_phone character varying(20), suspended_at timestamp without time zone, suspended_by integer, suspended_reason text, terminated_at timestamp without time zone, terminated_by integer, terminated_reason text, scheduled_purge_date date, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS loan_installments (id SERIAL, loan_id integer NOT NULL, installment_number integer NOT NULL, due_date date NOT NULL, scheduled_amount numeric(15,2) NOT NULL, payment_date date, amount_paid numeric(15,2), paid_bank character varying(150), payment_description text, status character varying(20) NOT NULL DEFAULT 'PENDING'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS loans (id SERIAL, loan_account_number character varying(100) NOT NULL, borrower_name character varying(200) NOT NULL, bank_name character varying(150) NOT NULL, loan_amount numeric(15,2) NOT NULL, total_installments integer NOT NULL, monthly_installment_amount numeric(15,2) NOT NULL, interest_rate numeric(5,2), loan_type character varying(50) NOT NULL DEFAULT 'BUSINESS'::character varying, start_date date NOT NULL, calculated_end_date date NOT NULL, status character varying(20) NOT NULL DEFAULT 'ACTIVE'::character varying, notes text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS note_shares (id SERIAL, note_id integer NOT NULL, shared_with_user_id integer NOT NULL, permission character varying(10) DEFAULT 'read'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS notes (id SERIAL, user_id integer NOT NULL, title character varying(200) NOT NULL, content text, color character varying(20) DEFAULT '#ffffff'::character varying, is_pinned boolean DEFAULT false, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payables (payable_id SERIAL, vendor_id integer NOT NULL, payable_name character varying(150) NOT NULL, description text, payable_type character varying(20), amount numeric(12,2) NOT NULL, frequency character varying(20), start_date date, end_date date, contract_id integer, bank_account_id integer, payment_method character varying(50), reference_number character varying(100), is_active boolean DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS payment_payables (payment_id SERIAL, payable_id integer, payment_method character varying(50), bank_account_id integer, payment_date date DEFAULT CURRENT_DATE, amount numeric(12,2) NOT NULL, reference_number character varying(100), status character varying(50) DEFAULT 'Pending'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS petty_cash_account (id SERIAL, account_name character varying(100) DEFAULT 'Petty Cash'::character varying, current_balance numeric(15,2) DEFAULT 0.00, monthly_float_amount numeric(15,2) DEFAULT 0.00, last_replenished_date date, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS petty_cash_transactions (id SERIAL, petty_cash_account_id integer, transaction_type character varying(50) NOT NULL, amount numeric(15,2) NOT NULL, description text, project_id integer, source_bank_account_id integer, payable_id integer, transaction_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS projects (project_id SERIAL, project_name character varying(200) NOT NULL, project_description text, status character varying(50) DEFAULT 'active'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS pto_requests (id SERIAL, employee_id integer NOT NULL, manager_id integer, absence_type character varying(50) NOT NULL, from_date date NOT NULL, to_date date NOT NULL, total_hours numeric(6,2) NOT NULL, project_id integer, cover_person_id integer, cover_person_name character varying(200), description text, status character varying(20) DEFAULT 'pending'::character varying, manager_comments text, approved_at timestamp without time zone, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchase_order_items (id SERIAL, purchase_order_id integer, quantity integer NOT NULL, description text NOT NULL, unit_price numeric(12,2) NOT NULL, total numeric(12,2) NOT NULL, line_order integer DEFAULT 0, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS purchase_orders (id SERIAL, po_number character varying(50) NOT NULL, requested_by_user_id integer, requested_by_name character varying(255), requested_by_title character varying(255), vendor_id integer, vendor_invoice_number character varying(100), project_id integer, subtotal numeric(12,2) DEFAULT 0, sales_tax numeric(12,2) DEFAULT 0, shipping_handling numeric(12,2) DEFAULT 0, banking_fee numeric(12,2) DEFAULT 0, total_amount numeric(12,2) NOT NULL, payment_method character varying(50), check_number character varying(100), payment_amount numeric(12,2), payment_date date, status character varying(50) DEFAULT 'PENDING'::character varying, approved_by_user_id integer, approved_by_name character varying(255), approved_by_title character varying(255), approved_at timestamp without time zone, rejection_reason text, receipt_document_url text, receipt_uploaded_at timestamp without time zone, notes text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS quote_additional_services (service_id SERIAL, quote_id integer, service_name character varying(200) NOT NULL, price numeric(12,2) NOT NULL);
CREATE TABLE IF NOT EXISTS quote_items (item_id SERIAL, quote_id integer, description character varying(200) NOT NULL, quantity integer NOT NULL DEFAULT 1, unit_price numeric(12,2) NOT NULL, total numeric(12,2) NOT NULL);
CREATE TABLE IF NOT EXISTS quote_reminder_settings (setting_id SERIAL, days_after_sent integer NOT NULL DEFAULT 3, days_after_follow_up integer NOT NULL DEFAULT 7, enable_email_notifications boolean DEFAULT true, enable_dashboard_notifications boolean DEFAULT true, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS quote_reminders (reminder_id SERIAL, quote_id integer NOT NULL, reminder_date date NOT NULL, reminder_type character varying(20) DEFAULT 'MANUAL'::character varying, reminder_status character varying(20) DEFAULT 'PENDING'::character varying, created_by integer, notes text, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS quote_status_history (history_id SERIAL, quote_id integer, old_status character varying(20), new_status character varying(20), changed_by integer, notes text, changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS quotes (quote_id SERIAL, quote_number character varying(20) NOT NULL, template_type character varying(20), company_name character varying(200) NOT NULL, company_address text, date_of_issue date NOT NULL, subtotal numeric(12,2) NOT NULL, total_due numeric(12,2) NOT NULL, notes text, status character varying(20) DEFAULT 'DRAFT'::character varying, assigned_to integer, created_by integer, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS receivables (receivable_id SERIAL, payer_name character varying(150) NOT NULL, receivable_name character varying(150) NOT NULL, description text, receivable_type character varying(50), amount numeric(12,2) NOT NULL, frequency character varying(50), start_date date, end_date date, contract_id integer, is_active boolean DEFAULT true, bank_account_id integer, payment_method character varying(50), reference_number character varying(100), created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS subscriptions (id SERIAL, description character varying(200) NOT NULL, amount numeric(12,2) NOT NULL, due_date date NOT NULL, frequency character varying(20), auto_pay boolean DEFAULT false, is_active boolean DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS time_entries (id SERIAL, employee_id integer, project_id integer, contract_id integer, date date NOT NULL, clock_in timestamp without time zone, clock_out timestamp without time zone, total_hours numeric(5,2), break_time_minutes integer DEFAULT 0, description text, status character varying(20) DEFAULT 'pending'::character varying, approved_by integer, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS todo_shares (id SERIAL, todo_id integer NOT NULL, shared_with_user_id integer NOT NULL, permission character varying(10) DEFAULT 'read'::character varying, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS todos (id SERIAL, user_id integer NOT NULL, title character varying(200) NOT NULL, description text, status character varying(20) DEFAULT 'pending'::character varying, priority character varying(10) DEFAULT 'medium'::character varying, due_date date, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP, updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS vendors (vendor_id SERIAL, vendor_name character varying(150) NOT NULL, contact_email character varying(100), contact_phone character varying(30), is_active boolean DEFAULT true, created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP);
